### ISSUE TITLE
[Feature Request] Toggle visibility of left ribbon icons with style settings

### ISSUE THREAD

**Issue by jsmorabito** [chetachiezikeuzor/Yin-and-Yang-Theme#45]
If it's possible to hide individual icons in the left ribbon I think that'd be very convenient to access from the style settings menu for the Y&Y theme! I don't know how to target the individual icons with css but if its possible and you figure out the way I'd be happy to create css snippets for each icon to share with the obsidian community

**Comment by chetachiezikeuzor** [comment]
This isn't really possible, because I can't declare which commands you have in your side bar, since I don't know what plugins the user has installed, or how many. To have a toggle for each icon would be far too cumbersome to include in Style Settings. That would require having over 25 toggles just for hiding icons. If you want to hide individual icons you can use the snippet below, and change the aria label to match the command/plugin. I don't think it's a good idea to make a snippet for each of them either. I think it's better having your own snippet for the icons you want hidden without using Style Settings, so you can edit externally rather than having to open settings over and over. The user can duplicate the snippet themselves to fit their needs, rather than having a snippet for icons they may not even have installed and/or don't want to hide. 

```css
.workspace-ribbon.mod-left .side-dock-ribbon-action[aria-label="Alternative File Tree Plugin"]{
  display: none;
}
```

**Comment by jsmorabito** [comment]
oh wow. much more complicated than thought. thanks for explaining and for the snippet 🙏 seems like an option that's better left to the plugin creators to put in their own plugins settings menu
