### ISSUE TITLE
Using Obsidian_to_Anki, there is a problem with the list display.

### ISSUE THREAD

**Issue by LoveOctocat** [chetachiezikeuzor/Yin-and-Yang-Theme#63]
When the theme is used with the [Obsidian_to_Anki](https://github.com/Pseudonium/Obsidian_to_Anki) plugin, there is a problem with the list display.

This is the location where the Obsidian to Anki plugin is added by default.

![image](https://user-images.githubusercontent.com/19794638/137566430-5703cce9-0e5d-4dd4-b50c-ca24a291f7e0.png)

Here is the preview

![image](https://user-images.githubusercontent.com/19794638/137566459-d812936d-d8f6-4182-b8c2-99e4979dda48.png)

Add a blank line

![image](https://user-images.githubusercontent.com/19794638/137566487-87444d59-747a-49f6-bc95-452c00c953eb.png)

Here is the preview

![image](https://user-images.githubusercontent.com/19794638/137566494-ed88b3a0-3f17-48d4-85cd-3495e5bb7e83.png)

But in the second case, I can't use Obsidian_to_anki to synchronize when I change the content in the list.

**Comment by chetachiezikeuzor** [comment]
I apologize If I'm not understanding the issue here (I've never used Anki before so I'm completely unaware of this plugin). Is the issue that you need to have `<!--ID:` in order for the plugin to work, but it is negatively affecting list display while using Y&Y? Forgive me if I'm wrong here but is this not the case with using Default theme? I'm just not sure if this has to do with he theme, or just with the way Obsidian renders lists.

**Comment by LoveOctocat** [comment]
Sorry, the default theme has this problem too. I was wondering if it is possible to get a third party theme to fix this issue.
