### ISSUE TITLE
Add math symbol support for the editor mode

### ISSUE THREAD

**Issue by AvijeetPrasad** [chetachiezikeuzor/Yin-and-Yang-Theme#8]
This is an enhancement request. It would be nice if the editor mode can also render math symbols using mathjax. Right now a math symbol like $S_\nu$ just renders as S in the editor mode while the preview mode renders it correctly.

**Comment by chetachiezikeuzor** [comment]
Because of how complex Obsidian's editor is, I'm afraid it just isn't possible to render math symbols like in preview mode. The best I can do is remove the formatting characters. See video below. 

<a href="https://www.loom.com/share/1a3f529ce27c4171905676040a9205bf"> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/1a3f529ce27c4171905676040a9205bf-with-play.gif"> </a>

**Comment by AvijeetPrasad** [comment]
I guess that would be useful too. Earlier only some of the letters were showing up and that was confusing. Thanks a lot!

**Comment by chetachiezikeuzor** [comment]
No problem!

**Comment by nanoir** [comment]
> I guess that would be useful too. Earlier only some of the letters were showing up and that was confusing. Thanks a lot!

May I know how the only-show-letters issue is settled?
